# Generated by Django 4.2.25 on 2025-11-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='position',
            field=models.CharField(choices=[('Member', 'member'), ('Manager', 'manager')], default='Member', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('concluido', 'Concluido'), ('em andamento', 'Em andamento')], default='Em andamento', max_length=100),
        ),
    ]
