# Generated by Django 4.2.25 on 2025-11-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_description_alter_membership_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='position',
            field=models.CharField(choices=[('member', 'Membro'), ('manager', 'Gerente')], default='Member', max_length=100),
        ),
    ]
